# Generated by Django 5.2.8 on 2026-01-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Libarian",
            new_name="Librarian",
        ),
    ]
