# Generated by Django 5.2.8 on 2026-02-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="published_date",
            new_name="publication_year",
        ),
    ]
